config/routes.rb
Kahless::Application.routes.draw do
  

  devise_for :admins
  root :to => 'quotes#index'
  match "/new" => "quotes#new"
  get  "/admin_page" => "quotes#admin_page"
  resources :quotes, only: [ :index, :new, :create, :update, :destroy]
  match "/picture" => "quotes#picture"
  get "/test_page" => "quotes#test_page"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  attr_accessible :authorized, :text
  validates :text, :presence => true, :uniqueness => true, :length => { :within => 10..150 }


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController

  def show

  end


  def index
    @quote = Quote.where(authorized: true).all.sample
  end


  def new
    @quote = Quote.new 
  end


  def create
    @quote = Quote.new(params[:quote])
   if  @quote.save
       redirect_to root_path,  notice: "Your quote will be reviewed by the great Kahless"
   else
      render 'new'
      # redirect_to new_path, notice: "Please address the problems below."
   end  
  end
  
  def admin_page
    @quote = Quote.where(authorized: false)
  end

  def update
    @quote = Quote.find(params[:id])
    @quote.authorized = true
    @quote.save
    redirect_to admin_page_path
  end
  
  def picture
    
  end
  
  def destroy
    @quote = Quote.find(params[:id])
    @quote.destroy
    redirect_to admin_page_path
  end
  
  def test_page

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
  
  def authorized?
    @quote.authorized == true
  end

end

app/views/layouts/_footer.html.erb
<div class="container"> 
<footer>
 <p> Created by:<%=link_to "Chad Jemmett: Follow me on Twitter", "https://twitter.com/chad_jemmett"%></p>
</footer>
</div>

app/views/layouts/_header.html.erb
<div class="navbar">
  <div class="navbar-inner navbar-fixed-top navbar-inverse">
    <a class="brand" <%= link_to "Wisdom of Kahless", root_path %></a>
    <ul class="nav">
      <li><a <%= link_to "+ your own widsom", new_path %></a></li> 
      <li><%= link_to "Image of Kahless provided by Carl Jemmett", picture_path %></li>
      <li><a <%= link_to "Legend of Kahless", "http://en.memory-alpha.org/wiki/Kahless_the_Unforgettable" %></a></li>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wisdom of Kahless</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="containter">
    <%= render 'layouts/header' %>
  </div>
  <center>
  <div class="container">
    <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
    <% end %>
  </div>
<%= yield %> 
<div class="containter">

  <%= render 'layouts/footer' %>
</div>
  </center>
</body>
</html>

app/views/quotes/admin_page.html.erb
<% unless admin_signed_in? %>
<h1>Admin Only Page<h1>

<% else %>
<div class="container">
  <%= link_to "Sign out", destroy_admin_session_path, method: :delete, class: "btn btn-primary" %></br>
    <% @quote.each do |q| %>
  <table class="table table-striped">
     <tr>
       <td><%=q.text %></td>
       <td><%= q.authorized %></td>
       <td><%= link_to "Authorize", quote_path(q), method: :put, class: "btn" %></td>
       <td><%= link_to "Delete", q,  method: :delete, data: {confirm: "Are you sure?"}, class: "btn" %>
     </tr>
  </table>
  <% end %>
</div>
<% end %>

app/views/quotes/index.html.erb
<div class="container">
  <div class="span3"><%= link_to(image_tag("kahless3_sm.jpg", title: "Artist: Carl Jemmett"), picture_path) %></div>
  <div class="span5">
    <h2><%= @quote.text %></h2>
  </div>


  <div class="container">
    <center>
  <%= button_to "More Wisdom", root_path, class: "btn btn-large btn-primary"  %>
    </center>

  </div>
</div>

app/views/quotes/new.html.erb
<h1>Add your own wisdom</h1>


<%= form_for @quote do |f| %>
  <%= render "shared/error_messages", object: @quote %> 
  <div class="container">
    <%= f.text_area :text %></br>
    <%= f.submit %>
    <% end %>
  </div>

app/views/quotes/picture.html.erb
<div class="container">
  <h3>This drawing was made by my cousin, Carl Jemmett. He's an illustrator and animator with a background in IT.
  You can e-mail him at carlton.jemmett [at] gmail dot com.
  Or<%= link_to " check out his work on Deviant Art.", "http://cactuscarlton.deviantart.com/" %>.</h3>
</div>
<%= link_to(image_tag("kahless3.jpg", title: "Carl Jemmett"), "http://cactuscarlton.deviantart.com") %>

app/views/quotes/test_page.html.erb
<p>just a test page to test my controller testing.</p>

app/views/shared/_error_messages.html.erb
<% if  @quote.errors.any? %>
  <div id="errorsExplanation">
  <p>The form contains <%= pluralize(@quote.errors.count, "error") %>

    <ul>
      <% @quote.errors.full_messages.each do |msg| %>
        <li> <%= msg %> </li>
      <% end %>
    </ul>
  </div>
<% end %>